// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.repository;

import com.bantanger.im.domain.groupddd.ImGroup;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImGroupRepository extends BaseRepository<ImGroup, Long> {
}
