// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.repository;

import com.bantanger.im.domain.groupddd.ImGroupMember;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImGroupMemberRepository extends BaseRepository<ImGroupMember, Long> {
}
