// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.messageddd.creator.ImMessageHistoryCreator;
import com.bantanger.im.domain.messageddd.query.ImMessageHistoryQuery;
import com.bantanger.im.domain.messageddd.updater.ImMessageHistoryUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageHistoryVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImMessageHistoryService {
   /**
    * create
    */
   Long createImMessageHistory(ImMessageHistoryCreator creator);

   /**
    * update
    */
   void updateImMessageHistory(ImMessageHistoryUpdater updater);

   /**
    * valid
    */
   void validImMessageHistory(Long id);

   /**
    * invalid
    */
   void invalidImMessageHistory(Long id);

   /**
    * findById
    */
   ImMessageHistoryVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImMessageHistoryVO> findByPage(PageRequestWrapper<ImMessageHistoryQuery> query);
}
