// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.messageddd.ImMessageBody;
import com.bantanger.im.domain.messageddd.creator.ImMessageBodyCreator;
import com.bantanger.im.domain.messageddd.mapper.ImMessageBodyMapper;
import com.bantanger.im.domain.messageddd.query.ImMessageBodyQuery;
import com.bantanger.im.domain.messageddd.repository.ImMessageBodyRepository;
import com.bantanger.im.domain.messageddd.updater.ImMessageBodyUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageBodyVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImMessageBodyServiceImpl implements ImMessageBodyService {
   private final ImMessageBodyRepository imMessageBodyRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImMessageBody(ImMessageBodyCreator creator) {
      Optional<ImMessageBody> imMessageBody = EntityOperations.doCreate(imMessageBodyRepository)
      .create(() -> ImMessageBodyMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imMessageBody.isPresent() ? imMessageBody.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImMessageBody(ImMessageBodyUpdater updater) {
      EntityOperations.doUpdate(imMessageBodyRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImMessageBody(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImMessageBody(Long id) {
      EntityOperations.doUpdate(imMessageBodyRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImMessageBody(Long id) {
      EntityOperations.doUpdate(imMessageBodyRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImMessageBodyVO findById(Long id) {
      Optional<ImMessageBody> imMessageBody =  imMessageBodyRepository.findById(id);
      return new ImMessageBodyVO(imMessageBody.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImMessageBodyVO> findByPage(PageRequestWrapper<ImMessageBodyQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImMessageBody> page = imMessageBodyRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImMessageBodyVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
