// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.messageddd.ImMessageHistory;
import com.bantanger.im.domain.messageddd.creator.ImMessageHistoryCreator;
import com.bantanger.im.domain.messageddd.mapper.ImMessageHistoryMapper;
import com.bantanger.im.domain.messageddd.query.ImMessageHistoryQuery;
import com.bantanger.im.domain.messageddd.repository.ImMessageHistoryRepository;
import com.bantanger.im.domain.messageddd.updater.ImMessageHistoryUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageHistoryVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImMessageHistoryServiceImpl implements ImMessageHistoryService {
   private final ImMessageHistoryRepository imMessageHistoryRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImMessageHistory(ImMessageHistoryCreator creator) {
      Optional<ImMessageHistory> imMessageHistory = EntityOperations.doCreate(imMessageHistoryRepository)
      .create(() -> ImMessageHistoryMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imMessageHistory.isPresent() ? imMessageHistory.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImMessageHistory(ImMessageHistoryUpdater updater) {
      EntityOperations.doUpdate(imMessageHistoryRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImMessageHistory(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImMessageHistory(Long id) {
      EntityOperations.doUpdate(imMessageHistoryRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImMessageHistory(Long id) {
      EntityOperations.doUpdate(imMessageHistoryRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImMessageHistoryVO findById(Long id) {
      Optional<ImMessageHistory> imMessageHistory =  imMessageHistoryRepository.findById(id);
      return new ImMessageHistoryVO(imMessageHistory.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImMessageHistoryVO> findByPage(PageRequestWrapper<ImMessageHistoryQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImMessageHistory> page = imMessageHistoryRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImMessageHistoryVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
