// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.messageddd.creator.ImMessageBodyCreator;
import com.bantanger.im.domain.messageddd.query.ImMessageBodyQuery;
import com.bantanger.im.domain.messageddd.updater.ImMessageBodyUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageBodyVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImMessageBodyService {
   /**
    * create
    */
   Long createImMessageBody(ImMessageBodyCreator creator);

   /**
    * update
    */
   void updateImMessageBody(ImMessageBodyUpdater updater);

   /**
    * valid
    */
   void validImMessageBody(Long id);

   /**
    * invalid
    */
   void invalidImMessageBody(Long id);

   /**
    * findById
    */
   ImMessageBodyVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImMessageBodyVO> findByPage(PageRequestWrapper<ImMessageBodyQuery> query);
}
