// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.userddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.userddd.creator.ImUserDataCreator;
import com.bantanger.im.domain.userddd.query.ImUserDataQuery;
import com.bantanger.im.domain.userddd.updater.ImUserDataUpdater;
import com.bantanger.im.domain.userddd.vo.ImUserDataVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImUserDataService {
   /**
    * create
    */
   Long createImUserData(ImUserDataCreator creator);

   /**
    * update
    */
   void updateImUserData(ImUserDataUpdater updater);

   /**
    * valid
    */
   void validImUserData(Long id);

   /**
    * invalid
    */
   void invalidImUserData(Long id);

   /**
    * findById
    */
   ImUserDataVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImUserDataVO> findByPage(PageRequestWrapper<ImUserDataQuery> query);
}
