// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.repository;

import com.bantanger.im.domain.messageddd.ImMessageHistory;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImMessageHistoryRepository extends BaseRepository<ImMessageHistory, Long> {
}
