// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShipGroup;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupCreator;
import com.bantanger.im.domain.friendshipddd.mapper.ImFriendShipGroupMapper;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupQuery;
import com.bantanger.im.domain.friendshipddd.repository.ImFriendShipGroupRepository;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImFriendShipGroupServiceImpl implements ImFriendShipGroupService {
   private final ImFriendShipGroupRepository imFriendShipGroupRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImFriendShipGroup(ImFriendShipGroupCreator creator) {
      Optional<ImFriendShipGroup> imFriendShipGroup = EntityOperations.doCreate(imFriendShipGroupRepository)
      .create(() -> ImFriendShipGroupMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imFriendShipGroup.isPresent() ? imFriendShipGroup.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImFriendShipGroup(ImFriendShipGroupUpdater updater) {
      EntityOperations.doUpdate(imFriendShipGroupRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImFriendShipGroup(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImFriendShipGroup(Long id) {
      EntityOperations.doUpdate(imFriendShipGroupRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImFriendShipGroup(Long id) {
      EntityOperations.doUpdate(imFriendShipGroupRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImFriendShipGroupVO findById(Long id) {
      Optional<ImFriendShipGroup> imFriendShipGroup =  imFriendShipGroupRepository.findById(id);
      return new ImFriendShipGroupVO(imFriendShipGroup.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImFriendShipGroupVO> findByPage(PageRequestWrapper<ImFriendShipGroupQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImFriendShipGroup> page = imFriendShipGroupRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImFriendShipGroupVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
