// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShipGroupMember;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupMemberCreator;
import com.bantanger.im.domain.friendshipddd.mapper.ImFriendShipGroupMemberMapper;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupMemberQuery;
import com.bantanger.im.domain.friendshipddd.repository.ImFriendShipGroupMemberRepository;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupMemberUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupMemberVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImFriendShipGroupMemberServiceImpl implements ImFriendShipGroupMemberService {
   private final ImFriendShipGroupMemberRepository imFriendShipGroupMemberRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImFriendShipGroupMember(ImFriendShipGroupMemberCreator creator) {
      Optional<ImFriendShipGroupMember> imFriendShipGroupMember = EntityOperations.doCreate(imFriendShipGroupMemberRepository)
      .create(() -> ImFriendShipGroupMemberMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imFriendShipGroupMember.isPresent() ? imFriendShipGroupMember.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImFriendShipGroupMember(ImFriendShipGroupMemberUpdater updater) {
      EntityOperations.doUpdate(imFriendShipGroupMemberRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImFriendShipGroupMember(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImFriendShipGroupMember(Long id) {
      EntityOperations.doUpdate(imFriendShipGroupMemberRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImFriendShipGroupMember(Long id) {
      EntityOperations.doUpdate(imFriendShipGroupMemberRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImFriendShipGroupMemberVO findById(Long id) {
      Optional<ImFriendShipGroupMember> imFriendShipGroupMember =  imFriendShipGroupMemberRepository.findById(id);
      return new ImFriendShipGroupMemberVO(imFriendShipGroupMember.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImFriendShipGroupMemberVO> findByPage(
         PageRequestWrapper<ImFriendShipGroupMemberQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImFriendShipGroupMember> page = imFriendShipGroupMemberRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImFriendShipGroupMemberVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
