// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipRequestCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipRequestQuery;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipRequestUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipRequestVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImFriendShipRequestService {
   /**
    * create
    */
   Long createImFriendShipRequest(ImFriendShipRequestCreator creator);

   /**
    * update
    */
   void updateImFriendShipRequest(ImFriendShipRequestUpdater updater);

   /**
    * valid
    */
   void validImFriendShipRequest(Long id);

   /**
    * invalid
    */
   void invalidImFriendShipRequest(Long id);

   /**
    * findById
    */
   ImFriendShipRequestVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImFriendShipRequestVO> findByPage(PageRequestWrapper<ImFriendShipRequestQuery> query);
}
