// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipQuery;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImFriendShipService {
   /**
    * create
    */
   Long createImFriendShip(ImFriendShipCreator creator);

   /**
    * update
    */
   void updateImFriendShip(ImFriendShipUpdater updater);

   /**
    * valid
    */
   void validImFriendShip(Long id);

   /**
    * invalid
    */
   void invalidImFriendShip(Long id);

   /**
    * findById
    */
   ImFriendShipVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImFriendShipVO> findByPage(PageRequestWrapper<ImFriendShipQuery> query);
}
