// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupQuery;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImFriendShipGroupService {
   /**
    * create
    */
   Long createImFriendShipGroup(ImFriendShipGroupCreator creator);

   /**
    * update
    */
   void updateImFriendShipGroup(ImFriendShipGroupUpdater updater);

   /**
    * valid
    */
   void validImFriendShipGroup(Long id);

   /**
    * invalid
    */
   void invalidImFriendShipGroup(Long id);

   /**
    * findById
    */
   ImFriendShipGroupVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImFriendShipGroupVO> findByPage(PageRequestWrapper<ImFriendShipGroupQuery> query);
}
