// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupMemberCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupMemberQuery;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupMemberUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupMemberVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImFriendShipGroupMemberService {
   /**
    * create
    */
   Long createImFriendShipGroupMember(ImFriendShipGroupMemberCreator creator);

   /**
    * update
    */
   void updateImFriendShipGroupMember(ImFriendShipGroupMemberUpdater updater);

   /**
    * valid
    */
   void validImFriendShipGroupMember(Long id);

   /**
    * invalid
    */
   void invalidImFriendShipGroupMember(Long id);

   /**
    * findById
    */
   ImFriendShipGroupMemberVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImFriendShipGroupMemberVO> findByPage(
         PageRequestWrapper<ImFriendShipGroupMemberQuery> query);
}
