// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShip;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipCreator;
import com.bantanger.im.domain.friendshipddd.mapper.ImFriendShipMapper;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipQuery;
import com.bantanger.im.domain.friendshipddd.repository.ImFriendShipRepository;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImFriendShipServiceImpl implements ImFriendShipService {
   private final ImFriendShipRepository imFriendShipRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImFriendShip(ImFriendShipCreator creator) {
      Optional<ImFriendShip> imFriendShip = EntityOperations.doCreate(imFriendShipRepository)
      .create(() -> ImFriendShipMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imFriendShip.isPresent() ? imFriendShip.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImFriendShip(ImFriendShipUpdater updater) {
      EntityOperations.doUpdate(imFriendShipRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImFriendShip(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImFriendShip(Long id) {
      EntityOperations.doUpdate(imFriendShipRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImFriendShip(Long id) {
      EntityOperations.doUpdate(imFriendShipRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImFriendShipVO findById(Long id) {
      Optional<ImFriendShip> imFriendShip =  imFriendShipRepository.findById(id);
      return new ImFriendShipVO(imFriendShip.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImFriendShipVO> findByPage(PageRequestWrapper<ImFriendShipQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImFriendShip> page = imFriendShipRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImFriendShipVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
