// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.conversationddd.request;

import com.bantanger.common.model.AbstractImRequest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class ImConversationSetCreateRequest extends AbstractImRequest {
   @Schema(
         title = "会话ID"
   )
   private String conversationId;

   @Schema(
         title = "会话类型"
   )
   private Integer conversationType;

   @Schema(
         title = "消息来源方ID"
   )
   private String fromId;

   @Schema(
         title = "消息接收方ID"
   )
   private String toId;

   @Schema(
         title = "会话通知方式"
   )
   private Integer conversationNoticeType;

   @Schema(
         title = "会话显示位置"
   )
   private Integer conversationAppearsType;

   @Schema(
         title = "会话最新消息序列号"
   )
   private Long sequence;

   @Schema(
         title = "消息已读偏序"
   )
   private Long readSequence;

   @Schema(
         title = "用户所在APP"
   )
   private Integer appId;

   public String getConversationId() {
      return conversationId;
   }

   public void setConversationId(String conversationId) {
      this.conversationId = conversationId;
   }

   public Integer getConversationType() {
      return conversationType;
   }

   public void setConversationType(Integer conversationType) {
      this.conversationType = conversationType;
   }

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public String getToId() {
      return toId;
   }

   public void setToId(String toId) {
      this.toId = toId;
   }

   public Integer getConversationNoticeType() {
      return conversationNoticeType;
   }

   public void setConversationNoticeType(Integer conversationNoticeType) {
      this.conversationNoticeType = conversationNoticeType;
   }

   public Integer getConversationAppearsType() {
      return conversationAppearsType;
   }

   public void setConversationAppearsType(Integer conversationAppearsType) {
      this.conversationAppearsType = conversationAppearsType;
   }

   public Long getSequence() {
      return sequence;
   }

   public void setSequence(Long sequence) {
      this.sequence = sequence;
   }

   public Long getReadSequence() {
      return readSequence;
   }

   public void setReadSequence(Long readSequence) {
      this.readSequence = readSequence;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }
}
