// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.groupddd.ImGroup;
import com.bantanger.im.domain.groupddd.creator.ImGroupCreator;
import com.bantanger.im.domain.groupddd.query.ImGroupQuery;
import com.bantanger.im.domain.groupddd.request.ImGroupCreateRequest;
import com.bantanger.im.domain.groupddd.request.ImGroupQueryRequest;
import com.bantanger.im.domain.groupddd.request.ImGroupUpdateRequest;
import com.bantanger.im.domain.groupddd.response.ImGroupResponse;
import com.bantanger.im.domain.groupddd.updater.ImGroupUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImGroupMapper {
   ImGroupMapper INSTANCE = Mappers.getMapper(ImGroupMapper.class);

   ImGroup dtoToEntity(ImGroupCreator dto);

   ImGroupUpdater request2Updater(ImGroupUpdateRequest request);

   ImGroupCreator request2Dto(ImGroupCreateRequest request);

   ImGroupQuery request2Query(ImGroupQueryRequest request);

   ImGroupResponse vo2Response(ImGroupVO vo);

   default ImGroupResponse vo2CustomResponse(ImGroupVO vo) {
      ImGroupResponse response = vo2Response(vo);
      return response;
   }
}
