// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.groupddd.ImGroupMember;
import com.bantanger.im.domain.groupddd.creator.ImGroupMemberCreator;
import com.bantanger.im.domain.groupddd.query.ImGroupMemberQuery;
import com.bantanger.im.domain.groupddd.request.ImGroupMemberCreateRequest;
import com.bantanger.im.domain.groupddd.request.ImGroupMemberQueryRequest;
import com.bantanger.im.domain.groupddd.request.ImGroupMemberUpdateRequest;
import com.bantanger.im.domain.groupddd.response.ImGroupMemberResponse;
import com.bantanger.im.domain.groupddd.updater.ImGroupMemberUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupMemberVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImGroupMemberMapper {
   ImGroupMemberMapper INSTANCE = Mappers.getMapper(ImGroupMemberMapper.class);

   ImGroupMember dtoToEntity(ImGroupMemberCreator dto);

   ImGroupMemberUpdater request2Updater(ImGroupMemberUpdateRequest request);

   ImGroupMemberCreator request2Dto(ImGroupMemberCreateRequest request);

   ImGroupMemberQuery request2Query(ImGroupMemberQueryRequest request);

   ImGroupMemberResponse vo2Response(ImGroupMemberVO vo);

   default ImGroupMemberResponse vo2CustomResponse(ImGroupMemberVO vo) {
      ImGroupMemberResponse response = vo2Response(vo);
      return response;
   }
}
