// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.groupddd.ImGroupMember;
import com.bantanger.im.domain.groupddd.creator.ImGroupMemberCreator;
import com.bantanger.im.domain.groupddd.mapper.ImGroupMemberMapper;
import com.bantanger.im.domain.groupddd.query.ImGroupMemberQuery;
import com.bantanger.im.domain.groupddd.repository.ImGroupMemberRepository;
import com.bantanger.im.domain.groupddd.updater.ImGroupMemberUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupMemberVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImGroupMemberServiceImpl implements ImGroupMemberService {
   private final ImGroupMemberRepository imGroupMemberRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImGroupMember(ImGroupMemberCreator creator) {
      Optional<ImGroupMember> imGroupMember = EntityOperations.doCreate(imGroupMemberRepository)
      .create(() -> ImGroupMemberMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imGroupMember.isPresent() ? imGroupMember.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImGroupMember(ImGroupMemberUpdater updater) {
      EntityOperations.doUpdate(imGroupMemberRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImGroupMember(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImGroupMember(Long id) {
      EntityOperations.doUpdate(imGroupMemberRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImGroupMember(Long id) {
      EntityOperations.doUpdate(imGroupMemberRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImGroupMemberVO findById(Long id) {
      Optional<ImGroupMember> imGroupMember =  imGroupMemberRepository.findById(id);
      return new ImGroupMemberVO(imGroupMember.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImGroupMemberVO> findByPage(PageRequestWrapper<ImGroupMemberQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImGroupMember> page = imGroupMemberRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImGroupMemberVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
