// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.groupddd.creator.ImGroupCreator;
import com.bantanger.im.domain.groupddd.query.ImGroupQuery;
import com.bantanger.im.domain.groupddd.updater.ImGroupUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImGroupService {
   /**
    * create
    */
   Long createImGroup(ImGroupCreator creator);

   /**
    * update
    */
   void updateImGroup(ImGroupUpdater updater);

   /**
    * valid
    */
   void validImGroup(Long id);

   /**
    * invalid
    */
   void invalidImGroup(Long id);

   /**
    * findById
    */
   ImGroupVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImGroupVO> findByPage(PageRequestWrapper<ImGroupQuery> query);
}
