// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.groupddd.ImGroup;
import com.bantanger.im.domain.groupddd.creator.ImGroupCreator;
import com.bantanger.im.domain.groupddd.mapper.ImGroupMapper;
import com.bantanger.im.domain.groupddd.query.ImGroupQuery;
import com.bantanger.im.domain.groupddd.repository.ImGroupRepository;
import com.bantanger.im.domain.groupddd.updater.ImGroupUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ImGroupServiceImpl implements ImGroupService {
   private final ImGroupRepository imGroupRepository;

   /**
    * createImpl
    */
   @Override
   public Long createImGroup(ImGroupCreator creator) {
      Optional<ImGroup> imGroup = EntityOperations.doCreate(imGroupRepository)
      .create(() -> ImGroupMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return imGroup.isPresent() ? imGroup.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateImGroup(ImGroupUpdater updater) {
      EntityOperations.doUpdate(imGroupRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateImGroup(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validImGroup(Long id) {
      EntityOperations.doUpdate(imGroupRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidImGroup(Long id) {
      EntityOperations.doUpdate(imGroupRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ImGroupVO findById(Long id) {
      Optional<ImGroup> imGroup =  imGroupRepository.findById(id);
      return new ImGroupVO(imGroup.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ImGroupVO> findByPage(PageRequestWrapper<ImGroupQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ImGroup> page = imGroupRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ImGroupVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
