// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.groupddd.creator.ImGroupMemberCreator;
import com.bantanger.im.domain.groupddd.query.ImGroupMemberQuery;
import com.bantanger.im.domain.groupddd.updater.ImGroupMemberUpdater;
import com.bantanger.im.domain.groupddd.vo.ImGroupMemberVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImGroupMemberService {
   /**
    * create
    */
   Long createImGroupMember(ImGroupMemberCreator creator);

   /**
    * update
    */
   void updateImGroupMember(ImGroupMemberUpdater updater);

   /**
    * valid
    */
   void validImGroupMember(Long id);

   /**
    * invalid
    */
   void invalidImGroupMember(Long id);

   /**
    * findById
    */
   ImGroupMemberVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImGroupMemberVO> findByPage(PageRequestWrapper<ImGroupMemberQuery> query);
}
