// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.conversationddd.repository;

import com.bantanger.im.domain.conversationddd.ImConversationSet;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImConversationSetRepository extends BaseRepository<ImConversationSet, Long> {
}
