// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImGroupResponse extends AbstractJpaResponse {
   @Schema(
         title = "群组ID"
   )
   private String groupId;

   @Schema(
         title = "应用ID"
   )
   private Integer appId;

   @Schema(
         title = "群主ID"
   )
   private String ownerId;

   @Schema(
         title = "群类型"
   )
   private Integer groupType;

   @Schema(
         title = "群名称"
   )
   private String groupName;

   @Schema(
         title = "是否全员禁言"
   )
   private Integer mute;

   @Schema(
         title = "申请加群类型"
   )
   private Integer applyJoinType;

   @Schema(
         title = "群简介"
   )
   private String introduction;

   @Schema(
         title = "群公告"
   )
   private String notification;

   @Schema(
         title = "群头像"
   )
   private String photo;

   @Schema(
         title = "群成员上限"
   )
   private Integer maxMemberCount;

   @Schema(
         title = "群状态"
   )
   private ValidStatus status;

   @Schema(
         title = "序列号"
   )
   private Long sequence;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getGroupId() {
      return groupId;
   }

   public void setGroupId(String groupId) {
      this.groupId = groupId;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public String getOwnerId() {
      return ownerId;
   }

   public void setOwnerId(String ownerId) {
      this.ownerId = ownerId;
   }

   public Integer getGroupType() {
      return groupType;
   }

   public void setGroupType(Integer groupType) {
      this.groupType = groupType;
   }

   public String getGroupName() {
      return groupName;
   }

   public void setGroupName(String groupName) {
      this.groupName = groupName;
   }

   public Integer getMute() {
      return mute;
   }

   public void setMute(Integer mute) {
      this.mute = mute;
   }

   public Integer getApplyJoinType() {
      return applyJoinType;
   }

   public void setApplyJoinType(Integer applyJoinType) {
      this.applyJoinType = applyJoinType;
   }

   public String getIntroduction() {
      return introduction;
   }

   public void setIntroduction(String introduction) {
      this.introduction = introduction;
   }

   public String getNotification() {
      return notification;
   }

   public void setNotification(String notification) {
      this.notification = notification;
   }

   public String getPhoto() {
      return photo;
   }

   public void setPhoto(String photo) {
      this.photo = photo;
   }

   public Integer getMaxMemberCount() {
      return maxMemberCount;
   }

   public void setMaxMemberCount(Integer maxMemberCount) {
      this.maxMemberCount = maxMemberCount;
   }

   public ValidStatus getStatus() {
      return status;
   }

   public void setStatus(ValidStatus status) {
      this.status = status;
   }

   public Long getSequence() {
      return sequence;
   }

   public void setSequence(Long sequence) {
      this.sequence = sequence;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
