// --- Auto Generated by BanTanger ---
package com.bantanger.im.domain.user.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ImUserDataQueryRequest implements Request {
}
