// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.controller;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.model.JsonObject;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.common.model.PageResult;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipRequestCreator;
import com.bantanger.im.domain.friendshipddd.mapper.ImFriendShipRequestMapper;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipRequestQuery;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestCreateRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestQueryRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestUpdateRequest;
import com.bantanger.im.domain.friendshipddd.response.ImFriendShipRequestResponse;
import com.bantanger.im.domain.friendshipddd.service.ImFriendShipRequestService;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipRequestUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipRequestVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("imFriendShipRequest/v1/")
@RequiredArgsConstructor
public class ImFriendShipRequestController {
   private final ImFriendShipRequestService imFriendShipRequestService;

   /**
    * createRequest
    */
   @PostMapping("createImFriendShipRequest")
   public JsonObject<Long> createImFriendShipRequest(
         @RequestBody ImFriendShipRequestCreateRequest request) {
      ImFriendShipRequestCreator creator = ImFriendShipRequestMapper.INSTANCE.request2Dto(request);
      return JsonObject.success(imFriendShipRequestService.createImFriendShipRequest(creator));
   }

   /**
    * update request
    */
   @PostMapping("updateImFriendShipRequest")
   public JsonObject<String> updateImFriendShipRequest(
         @RequestBody ImFriendShipRequestUpdateRequest request) {
      ImFriendShipRequestUpdater updater = ImFriendShipRequestMapper.INSTANCE.request2Updater(request);
      imFriendShipRequestService.updateImFriendShipRequest(updater);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * valid
    */
   @PostMapping("valid/{id}")
   public JsonObject<String> validImFriendShipRequest(@PathVariable Long id) {
      imFriendShipRequestService.validImFriendShipRequest(id);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * invalid
    */
   @PostMapping("invalid/{id}")
   public JsonObject<String> invalidImFriendShipRequest(@PathVariable Long id) {
      imFriendShipRequestService.invalidImFriendShipRequest(id);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * findById
    */
   @GetMapping("findById/{id}")
   public JsonObject<ImFriendShipRequestResponse> findById(@PathVariable Long id) {
      ImFriendShipRequestVO vo = imFriendShipRequestService.findById(id);
      ImFriendShipRequestResponse response = ImFriendShipRequestMapper.INSTANCE.vo2CustomResponse(vo);
      return JsonObject.success(response);
   }

   /**
    * findByPage request
    */
   @PostMapping("findByPage")
   public JsonObject<PageResult<ImFriendShipRequestResponse>> findByPage(
         @RequestBody PageRequestWrapper<ImFriendShipRequestQueryRequest> request) {
      PageRequestWrapper<ImFriendShipRequestQuery> wrapper = new PageRequestWrapper<>();
      wrapper.setBean(ImFriendShipRequestMapper.INSTANCE.request2Query(request.getBean()));
      wrapper.setSorts(request.getSorts());
          wrapper.setPageSize(request.getPageSize());
          wrapper.setPage(request.getPage());
      Page<ImFriendShipRequestVO> page = imFriendShipRequestService.findByPage(wrapper);
      return JsonObject.success(
              PageResult.of(
                  page.getContent().stream()
                      .map(vo -> ImFriendShipRequestMapper.INSTANCE.vo2CustomResponse(vo))
                      .collect(Collectors.toList()),
                  page.getTotalElements(),
                  page.getSize(),
                  page.getNumber())
          );
   }
}
