// --- Auto Generated by BanTanger ---
package com.bantanger.im.domain.user.repository;

import com.bantanger.im.domain.user.ImUserData;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImUserDataRepository extends BaseRepository<ImUserData, Long> {
}
