// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.request;

import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImMessageBodyCreateRequest extends AbstractImRequest {
   @Schema(
         title = "唯一ID标识"
   )
   private Long messageKey;

   @Schema(
         title = "messageBody"
   )
   private String messageBody;

   @Schema(
         title = "messageTime"
   )
   private Long messageTime;

   @Schema(
         title = "用户所在APP"
   )
   private Integer appId;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   public Long getMessageKey() {
      return messageKey;
   }

   public void setMessageKey(Long messageKey) {
      this.messageKey = messageKey;
   }

   public String getMessageBody() {
      return messageBody;
   }

   public void setMessageBody(String messageBody) {
      this.messageBody = messageBody;
   }

   public Long getMessageTime() {
      return messageTime;
   }

   public void setMessageTime(Long messageTime) {
      this.messageTime = messageTime;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }
}
