// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.request;

import com.bantanger.common.model.AbstractImRequest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class ImMessageHistoryUpdateRequest extends AbstractImRequest {
   @Schema(
         title = "消息类型"
   )
   private Integer msgType;

   @Schema(
         title = "消息来源方ID"
   )
   private String fromId;

   @Schema(
         title = "消息接收方ID"
   )
   private String toId;

   @Schema(
         title = "消息序列号（相对序列）"
   )
   private Long sequence;

   @Schema(
         title = "消息加密密钥"
   )
   private String messageSecurityKey;

   @Schema(
         title = "消息拥有者，写扩散标识写入哪个消息队列"
   )
   private String ownerId;

   @Schema(
         title = "messageTime"
   )
   private Long messageTime;

   private Long id;

   public Integer getMsgType() {
      return msgType;
   }

   public void setMsgType(Integer msgType) {
      this.msgType = msgType;
   }

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public String getToId() {
      return toId;
   }

   public void setToId(String toId) {
      this.toId = toId;
   }

   public Long getSequence() {
      return sequence;
   }

   public void setSequence(Long sequence) {
      this.sequence = sequence;
   }

   public String getMessageSecurityKey() {
      return messageSecurityKey;
   }

   public void setMessageSecurityKey(String messageSecurityKey) {
      this.messageSecurityKey = messageSecurityKey;
   }

   public String getOwnerId() {
      return ownerId;
   }

   public void setOwnerId(String ownerId) {
      this.ownerId = ownerId;
   }

   public Long getMessageTime() {
      return messageTime;
   }

   public void setMessageTime(Long messageTime) {
      this.messageTime = messageTime;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
