// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipGroupResponse extends AbstractJpaResponse {
   @Schema(
         title = "分组ID"
   )
   private Long groupId;

   @Schema(
         title = "创建者ID"
   )
   private String fromId;

   @Schema(
         title = "应用ID"
   )
   private Integer appId;

   @Schema(
         title = "分组名称"
   )
   private String groupName;

   @Schema(
         title = "创建时间"
   )
   private Long createTime;

   @Schema(
         title = "更新时间"
   )
   private Long updateTime;

   @Schema(
         title = "序列号"
   )
   private Long sequence;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public Long getGroupId() {
      return groupId;
   }

   public void setGroupId(Long groupId) {
      this.groupId = groupId;
   }

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public String getGroupName() {
      return groupName;
   }

   public void setGroupName(String groupName) {
      this.groupName = groupName;
   }

   public Long getCreateTime() {
      return createTime;
   }

   public void setCreateTime(Long createTime) {
      this.createTime = createTime;
   }

   public Long getUpdateTime() {
      return updateTime;
   }

   public void setUpdateTime(Long updateTime) {
      this.updateTime = updateTime;
   }

   public Long getSequence() {
      return sequence;
   }

   public void setSequence(Long sequence) {
      this.sequence = sequence;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
