// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipRequestCreateRequest extends AbstractImRequest {
   @Schema(
         title = "发送方ID"
   )
   private String fromId;

   @Schema(
         title = "接收方ID"
   )
   private String toId;

   @Schema(
         title = "好友来源"
   )
   private Integer addSource;

   @Schema(
         title = "好友来源描述"
   )
   private String addWording;

   @Schema(
         title = "好友来源描述"
   )
   private String remark;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   @Schema(
         title = "好友状态"
   )
   private Integer status;

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public String getToId() {
      return toId;
   }

   public void setToId(String toId) {
      this.toId = toId;
   }

   public Integer getAddSource() {
      return addSource;
   }

   public void setAddSource(Integer addSource) {
      this.addSource = addSource;
   }

   public String getAddWording() {
      return addWording;
   }

   public void setAddWording(String addWording) {
      this.addWording = addWording;
   }

   public String getRemark() {
      return remark;
   }

   public void setRemark(String remark) {
      this.remark = remark;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public Integer getStatus() {
      return status;
   }

   public void setStatus(Integer status) {
      this.status = status;
   }
}
