// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipGroupCreateRequest extends AbstractImRequest {
   @Schema(
         title = "分组ID"
   )
   private Long groupId;

   @Schema(
         title = "创建者ID"
   )
   private String fromId;

   @Schema(
         title = "应用ID"
   )
   private Integer appId;

   @Schema(
         title = "分组名称"
   )
   private String groupName;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   public Long getGroupId() {
      return groupId;
   }

   public void setGroupId(Long groupId) {
      this.groupId = groupId;
   }

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public String getGroupName() {
      return groupName;
   }

   public void setGroupName(String groupName) {
      this.groupName = groupName;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }
}
