// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipGroupUpdateRequest extends AbstractImRequest {
   @Schema(
         title = "分组ID"
   )
   private Long groupId;

   @Schema(
         title = "分组名称"
   )
   private String groupName;

   @Schema(
         title = "更新时间"
   )
   private Long updateTime;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   private Long id;

   public Long getGroupId() {
      return groupId;
   }

   public void setGroupId(Long groupId) {
      this.groupId = groupId;
   }

   public String getGroupName() {
      return groupName;
   }

   public void setGroupName(String groupName) {
      this.groupName = groupName;
   }

   public Long getUpdateTime() {
      return updateTime;
   }

   public void setUpdateTime(Long updateTime) {
      this.updateTime = updateTime;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
