// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipCreateRequest extends AbstractImRequest {
   @Schema(
         title = "应用ID"
   )
   private Integer appId;

   @Schema(
         title = "发起方ID"
   )
   private String fromId;

   @Schema(
         title = "接收方ID"
   )
   private String toId;

   @Schema(
         title = "备注"
   )
   private String remark;

   @Schema(
         title = "状态"
   )
   private ValidStatus status;

   @Schema(
         title = "黑名单状态"
   )
   private ValidStatus black;

   @Schema(
         title = "好友来源"
   )
   private String addSource;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public String getFromId() {
      return fromId;
   }

   public void setFromId(String fromId) {
      this.fromId = fromId;
   }

   public String getToId() {
      return toId;
   }

   public void setToId(String toId) {
      this.toId = toId;
   }

   public String getRemark() {
      return remark;
   }

   public void setRemark(String remark) {
      this.remark = remark;
   }

   public ValidStatus getStatus() {
      return status;
   }

   public void setStatus(ValidStatus status) {
      this.status = status;
   }

   public ValidStatus getBlack() {
      return black;
   }

   public void setBlack(ValidStatus black) {
      this.black = black;
   }

   public String getAddSource() {
      return addSource;
   }

   public void setAddSource(String addSource) {
      this.addSource = addSource;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }
}
