// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.model.AbstractImRequest;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ImFriendShipGroupMemberQueryRequest extends AbstractImRequest {
}
