// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.request;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImFriendShipUpdateRequest extends AbstractImRequest {
   @Schema(
         title = "备注"
   )
   private String remark;

   @Schema(
         title = "状态"
   )
   private ValidStatus status;

   @Schema(
         title = "黑名单状态"
   )
   private ValidStatus black;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   private Long id;

   public String getRemark() {
      return remark;
   }

   public void setRemark(String remark) {
      this.remark = remark;
   }

   public ValidStatus getStatus() {
      return status;
   }

   public void setStatus(ValidStatus status) {
      this.status = status;
   }

   public ValidStatus getBlack() {
      return black;
   }

   public void setBlack(ValidStatus black) {
      this.black = black;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
