// --- Auto Generated by BanTanger ---
package com.bantanger.im.domain.user.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.domain.user.ImUserData;
import com.bantanger.im.domain.user.creator.ImUserDataCreator;
import com.bantanger.im.domain.user.query.ImUserDataQuery;
import com.bantanger.im.domain.user.request.ImUserDataCreateRequest;
import com.bantanger.im.domain.user.request.ImUserDataQueryRequest;
import com.bantanger.im.domain.user.request.ImUserDataUpdateRequest;
import com.bantanger.im.domain.user.response.ImUserDataResponse;
import com.bantanger.im.domain.user.updater.ImUserDataUpdater;
import com.bantanger.im.domain.user.vo.ImUserDataVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface ImUserDataMapper {
   ImUserDataMapper INSTANCE = Mappers.getMapper(ImUserDataMapper.class);

   ImUserData dtoToEntity(ImUserDataCreator dto);

   ImUserDataUpdater request2Updater(ImUserDataUpdateRequest request);

   ImUserDataCreator request2Dto(ImUserDataCreateRequest request);

   ImUserDataQuery request2Query(ImUserDataQueryRequest request);

   ImUserDataResponse vo2Response(ImUserDataVO vo);

   default ImUserDataResponse vo2CustomResponse(ImUserDataVO vo) {
      ImUserDataResponse response = vo2Response(vo);
      return response;
   }
}
