// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.messageddd.ImMessageBody;
import com.bantanger.im.domain.messageddd.creator.ImMessageBodyCreator;
import com.bantanger.im.domain.messageddd.query.ImMessageBodyQuery;
import com.bantanger.im.domain.messageddd.request.ImMessageBodyCreateRequest;
import com.bantanger.im.domain.messageddd.request.ImMessageBodyQueryRequest;
import com.bantanger.im.domain.messageddd.request.ImMessageBodyUpdateRequest;
import com.bantanger.im.domain.messageddd.response.ImMessageBodyResponse;
import com.bantanger.im.domain.messageddd.updater.ImMessageBodyUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageBodyVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
          CustomMapper.class
      }
)
public interface ImMessageBodyMapper {
   ImMessageBodyMapper INSTANCE = Mappers.getMapper(ImMessageBodyMapper.class);

   ImMessageBody dtoToEntity(ImMessageBodyCreator dto);

   ImMessageBodyUpdater request2Updater(ImMessageBodyUpdateRequest request);

   ImMessageBodyCreator request2Dto(ImMessageBodyCreateRequest request);

   ImMessageBodyQuery request2Query(ImMessageBodyQueryRequest request);

   ImMessageBodyResponse vo2Response(ImMessageBodyVO vo);

   default ImMessageBodyResponse vo2CustomResponse(ImMessageBodyVO vo) {
      ImMessageBodyResponse response = vo2Response(vo);
      return response;
   }
}
