// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.messageddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.messageddd.ImMessageHistory;
import com.bantanger.im.domain.messageddd.creator.ImMessageHistoryCreator;
import com.bantanger.im.domain.messageddd.query.ImMessageHistoryQuery;
import com.bantanger.im.domain.messageddd.request.ImMessageHistoryCreateRequest;
import com.bantanger.im.domain.messageddd.request.ImMessageHistoryQueryRequest;
import com.bantanger.im.domain.messageddd.request.ImMessageHistoryUpdateRequest;
import com.bantanger.im.domain.messageddd.response.ImMessageHistoryResponse;
import com.bantanger.im.domain.messageddd.updater.ImMessageHistoryUpdater;
import com.bantanger.im.domain.messageddd.vo.ImMessageHistoryVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
          CustomMapper.class
      }
)
public interface ImMessageHistoryMapper {
   ImMessageHistoryMapper INSTANCE = Mappers.getMapper(ImMessageHistoryMapper.class);

   ImMessageHistory dtoToEntity(ImMessageHistoryCreator dto);

   ImMessageHistoryUpdater request2Updater(ImMessageHistoryUpdateRequest request);

   ImMessageHistoryCreator request2Dto(ImMessageHistoryCreateRequest request);

   ImMessageHistoryQuery request2Query(ImMessageHistoryQueryRequest request);

   ImMessageHistoryResponse vo2Response(ImMessageHistoryVO vo);

   default ImMessageHistoryResponse vo2CustomResponse(ImMessageHistoryVO vo) {
      ImMessageHistoryResponse response = vo2Response(vo);
      return response;
   }
}
