// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.conversationddd.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.im.domain.conversationddd.creator.ImConversationSetCreator;
import com.bantanger.im.domain.conversationddd.query.ImConversationSetQuery;
import com.bantanger.im.domain.conversationddd.updater.ImConversationSetUpdater;
import com.bantanger.im.domain.conversationddd.vo.ImConversationSetVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ImConversationSetService {
   /**
    * create
    */
   Long createImConversationSet(ImConversationSetCreator creator);

   /**
    * update
    */
   void updateImConversationSet(ImConversationSetUpdater updater);

   /**
    * valid
    */
   void validImConversationSet(Long id);

   /**
    * invalid
    */
   void invalidImConversationSet(Long id);

   /**
    * findById
    */
   ImConversationSetVO findById(Long id);

   /**
    * findByPage
    */
   Page<ImConversationSetVO> findByPage(PageRequestWrapper<ImConversationSetQuery> query);
}
