// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.repository;

import com.bantanger.im.domain.friendshipddd.ImFriendShipGroupMember;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImFriendShipGroupMemberRepository extends BaseRepository<ImFriendShipGroupMember, Long> {
}
