// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.repository;

import com.bantanger.im.domain.friendshipddd.ImFriendShip;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImFriendShipRepository extends BaseRepository<ImFriendShip, Long> {
}
