// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShipGroupMember;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupMemberCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupMemberQuery;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupMemberCreateRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupMemberQueryRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupMemberUpdateRequest;
import com.bantanger.im.domain.friendshipddd.response.ImFriendShipGroupMemberResponse;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupMemberUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupMemberVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImFriendShipGroupMemberMapper {
   ImFriendShipGroupMemberMapper INSTANCE = Mappers.getMapper(ImFriendShipGroupMemberMapper.class);

   ImFriendShipGroupMember dtoToEntity(ImFriendShipGroupMemberCreator dto);

   ImFriendShipGroupMemberUpdater request2Updater(ImFriendShipGroupMemberUpdateRequest request);

   ImFriendShipGroupMemberCreator request2Dto(ImFriendShipGroupMemberCreateRequest request);

   ImFriendShipGroupMemberQuery request2Query(ImFriendShipGroupMemberQueryRequest request);

   ImFriendShipGroupMemberResponse vo2Response(ImFriendShipGroupMemberVO vo);

   default ImFriendShipGroupMemberResponse vo2CustomResponse(ImFriendShipGroupMemberVO vo) {
      ImFriendShipGroupMemberResponse response = vo2Response(vo);
      return response;
   }
}
