// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShipRequest;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipRequestCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipRequestQuery;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestCreateRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestQueryRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipRequestUpdateRequest;
import com.bantanger.im.domain.friendshipddd.response.ImFriendShipRequestResponse;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipRequestUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipRequestVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImFriendShipRequestMapper {
   ImFriendShipRequestMapper INSTANCE = Mappers.getMapper(ImFriendShipRequestMapper.class);

   ImFriendShipRequest dtoToEntity(ImFriendShipRequestCreator dto);

   ImFriendShipRequestUpdater request2Updater(ImFriendShipRequestUpdateRequest request);

   ImFriendShipRequestCreator request2Dto(ImFriendShipRequestCreateRequest request);

   ImFriendShipRequestQuery request2Query(ImFriendShipRequestQueryRequest request);

   ImFriendShipRequestResponse vo2Response(ImFriendShipRequestVO vo);

   default ImFriendShipRequestResponse vo2CustomResponse(ImFriendShipRequestVO vo) {
      ImFriendShipRequestResponse response = vo2Response(vo);
      return response;
   }
}
