// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.friendshipddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.friendshipddd.ImFriendShipGroup;
import com.bantanger.im.domain.friendshipddd.creator.ImFriendShipGroupCreator;
import com.bantanger.im.domain.friendshipddd.query.ImFriendShipGroupQuery;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupCreateRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupQueryRequest;
import com.bantanger.im.domain.friendshipddd.request.ImFriendShipGroupUpdateRequest;
import com.bantanger.im.domain.friendshipddd.response.ImFriendShipGroupResponse;
import com.bantanger.im.domain.friendshipddd.updater.ImFriendShipGroupUpdater;
import com.bantanger.im.domain.friendshipddd.vo.ImFriendShipGroupVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImFriendShipGroupMapper {
   ImFriendShipGroupMapper INSTANCE = Mappers.getMapper(ImFriendShipGroupMapper.class);

   ImFriendShipGroup dtoToEntity(ImFriendShipGroupCreator dto);

   ImFriendShipGroupUpdater request2Updater(ImFriendShipGroupUpdateRequest request);

   ImFriendShipGroupCreator request2Dto(ImFriendShipGroupCreateRequest request);

   ImFriendShipGroupQuery request2Query(ImFriendShipGroupQueryRequest request);

   ImFriendShipGroupResponse vo2Response(ImFriendShipGroupVO vo);

   default ImFriendShipGroupResponse vo2CustomResponse(ImFriendShipGroupVO vo) {
      ImFriendShipGroupResponse response = vo2Response(vo);
      return response;
   }
}
