// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.groupddd.request;

import com.bantanger.common.model.AbstractImRequest;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class ImGroupMemberCreateRequest extends AbstractImRequest {
   @Schema(
         title = "应用ID"
   )
   private Integer appId;

   @Schema(
         title = "群组ID"
   )
   private String groupId;

   @Schema(
         title = "成员ID"
   )
   private String memberId;

   @Schema(
         title = "成员角色"
   )
   private Integer role;

   @Schema(
         title = "禁言时间"
   )
   private Long silenceTime;

   @Schema(
         title = "群昵称"
   )
   private String alias;

   @Schema(
         title = "离开时间"
   )
   private Long leaveTime;

   @Schema(
         title = "加入类型"
   )
   private String joinType;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public String getGroupId() {
      return groupId;
   }

   public void setGroupId(String groupId) {
      this.groupId = groupId;
   }

   public String getMemberId() {
      return memberId;
   }

   public void setMemberId(String memberId) {
      this.memberId = memberId;
   }

   public Integer getRole() {
      return role;
   }

   public void setRole(Integer role) {
      this.role = role;
   }

   public Long getSilenceTime() {
      return silenceTime;
   }

   public void setSilenceTime(Long silenceTime) {
      this.silenceTime = silenceTime;
   }

   public String getAlias() {
      return alias;
   }

   public void setAlias(String alias) {
      this.alias = alias;
   }

   public Long getLeaveTime() {
      return leaveTime;
   }

   public void setLeaveTime(Long leaveTime) {
      this.leaveTime = leaveTime;
   }

   public String getJoinType() {
      return joinType;
   }

   public void setJoinType(String joinType) {
      this.joinType = joinType;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }
}
