// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.userddd.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import java.util.List;

@Schema
public class ImUserDataResponse extends AbstractJpaResponse {
   @Schema(
         title = "用户名称"
   )
   private String nickName;

   @Schema(
         title = "位置"
   )
   private String location;

   @Schema(
         title = "生日"
   )
   private String birthDay;

   @Schema(
         title = "头像"
   )
   private String photo;

   @Schema(
         title = "性别"
   )
   private String userSex;

   @Schema(
         title = "个性签名"
   )
   private String selfSignature;

   @Schema(
         title = "加好友验证类型"
   )
   private Integer friendAllowType;

   @Schema(
         title = "管理员禁止用户添加加好友"
   )
   private ValidStatus disableAddFriend;

   @Schema(
         title = "禁用标识"
   )
   private ValidStatus forbiddenFlag;

   @Schema(
         title = "禁言标识"
   )
   private ValidStatus silentFlag;

   @Schema(
         title = "用户类型"
   )
   private Integer userType;

   @Schema(
         title = "用户所在APP"
   )
   private Integer appId;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extra;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getNickName() {
      return nickName;
   }

   public void setNickName(String nickName) {
      this.nickName = nickName;
   }

   public String getLocation() {
      return location;
   }

   public void setLocation(String location) {
      this.location = location;
   }

   public String getBirthDay() {
      return birthDay;
   }

   public void setBirthDay(String birthDay) {
      this.birthDay = birthDay;
   }

   public String getPhoto() {
      return photo;
   }

   public void setPhoto(String photo) {
      this.photo = photo;
   }

   public String getUserSex() {
      return userSex;
   }

   public void setUserSex(String userSex) {
      this.userSex = userSex;
   }

   public String getSelfSignature() {
      return selfSignature;
   }

   public void setSelfSignature(String selfSignature) {
      this.selfSignature = selfSignature;
   }

   public Integer getFriendAllowType() {
      return friendAllowType;
   }

   public void setFriendAllowType(Integer friendAllowType) {
      this.friendAllowType = friendAllowType;
   }

   public ValidStatus getDisableAddFriend() {
      return disableAddFriend;
   }

   public void setDisableAddFriend(ValidStatus disableAddFriend) {
      this.disableAddFriend = disableAddFriend;
   }

   public ValidStatus getForbiddenFlag() {
      return forbiddenFlag;
   }

   public void setForbiddenFlag(ValidStatus forbiddenFlag) {
      this.forbiddenFlag = forbiddenFlag;
   }

   public ValidStatus getSilentFlag() {
      return silentFlag;
   }

   public void setSilentFlag(ValidStatus silentFlag) {
      this.silentFlag = silentFlag;
   }

   public Integer getUserType() {
      return userType;
   }

   public void setUserType(Integer userType) {
      this.userType = userType;
   }

   public Integer getAppId() {
      return appId;
   }

   public void setAppId(Integer appId) {
      this.appId = appId;
   }

   public List<CodeValue> getExtra() {
      return extra;
   }

   public void setExtra(List<CodeValue> extra) {
      this.extra = extra;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
