// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.conversationddd.mapper;

import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.im.common.CustomMapper;
import com.bantanger.im.domain.conversationddd.ImConversationSet;
import com.bantanger.im.domain.conversationddd.creator.ImConversationSetCreator;
import com.bantanger.im.domain.conversationddd.query.ImConversationSetQuery;
import com.bantanger.im.domain.conversationddd.request.ImConversationSetCreateRequest;
import com.bantanger.im.domain.conversationddd.request.ImConversationSetQueryRequest;
import com.bantanger.im.domain.conversationddd.request.ImConversationSetUpdateRequest;
import com.bantanger.im.domain.conversationddd.response.ImConversationSetResponse;
import com.bantanger.im.domain.conversationddd.updater.ImConversationSetUpdater;
import com.bantanger.im.domain.conversationddd.vo.ImConversationSetVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class,
            CustomMapper.class
      }
)
public interface ImConversationSetMapper {
   ImConversationSetMapper INSTANCE = Mappers.getMapper(ImConversationSetMapper.class);

   ImConversationSet dtoToEntity(ImConversationSetCreator dto);

   ImConversationSetUpdater request2Updater(ImConversationSetUpdateRequest request);

   ImConversationSetCreator request2Dto(ImConversationSetCreateRequest request);

   ImConversationSetQuery request2Query(ImConversationSetQueryRequest request);

   ImConversationSetResponse vo2Response(ImConversationSetVO vo);

   default ImConversationSetResponse vo2CustomResponse(ImConversationSetVO vo) {
      ImConversationSetResponse response = vo2Response(vo);
      return response;
   }
}
