// --- Auto Generated by BanTanger ---
// --- Welcome to im-whale-shark ! ---
//
package com.bantanger.im.domain.userddd.repository;

import com.bantanger.im.domain.userddd.ImUserData;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ImUserDataRepository extends BaseRepository<ImUserData, Long> {
}
